### ISSUE TITLE
wrong dates no identification in problem

### ISSUE THREAD

**Issue by bobotong** [Frikster/EDS_converter#11]
![image](https://cloud.githubusercontent.com/assets/24418843/21698365/799b719a-d34b-11e6-8f2b-11da6d74e5c9.png)

The dates for this chunk are all wrong yet nothing was indicated.... and the patient ID is supposed to be 100402 not 100401

**Comment by Frikster** [comment]
So the patient ID being wrong was a brand new bug but it has now been fixed and I'll send over the fix once #1 has been dealt with since this is part of fixing it. 

Dates are wrong due to missing drugs. Fixed.
